name: taxi_app
description: اپلیکیشن تاکسی اینترنتی مخصوص افغانستان - سفیر
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # این خط را با رعایت دو فاصله از سمت چپ اضافه کن
  image_picker: ^1.0.7 
  
  # اگر از آیکون‌های اپل هم استفاده می‌کنی:
  cupertino_icons: ^1.0.6

  # مدیریت حالت
  provider: ^6.0.5

  # نقشه گوگل و مکان‌یابی
  google_maps_flutter: ^2.5.0
  geolocator: ^10.1.0
  geocoding: ^2.1.0

  # درخواست‌ها به سرور و API
  http: ^1.1.0

  # طراحی و آیکون‌ها
  flutter_svg: ^2.0.9
  cupertino_icons: ^1.0.8

  # پرداخت و لینک‌ها
  flutter_stripe: ^9.4.0
  url_launcher: ^6.2.4

  # ذخیره‌سازی و دیتابیس
  shared_preferences: ^2.2.2
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6

  # ابزارهای جانبی و انیمیشن
  animations: ^2.0.8
  form_field_validator: ^1.1.0
  image_picker: ^1.0.4
  path_provider: ^2.1.1
  flutter_polyline_points: ^2.0.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  # تعریف پوشه‌های تصاویر و آیکون‌ها
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/

  # تنظیمات فونت مدرن ایران‌یکان برای سفیر
  fonts:
    - family: IranYekan
      fonts:
        - asset: assets/fonts/Qs_Iranyekan.ttf
        - asset: assets/fonts/Qs_Iranyekan_light.ttf
          weight: 300
        - asset: assets/fonts/Qs_Iranyekan_bold.ttf
          weight: 700
